### ISSUE TITLE
Fix the PathExpr annotation

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#122]
# Issue

## Description

The PathExpr is at the moment only returning a sequence of nodes, it should return the type of the last node.

## Sub-tasks

Atomized tasks that cannot be broken down further.

- [x] Anotate the pathExpr correctly

**Comment by HectorPeeters** [comment]
This issue will also fix part of the simpleMapExpr annotation which is disabled for now
