### ISSUE TITLE
Implement type inference in comparison operator

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#42]
# Description

Implement type inference in comparison operator, the same way we did in binary operator. Only start when we are happy with binary operator as they are the same principle in implementation.

# Sub-tasks

- [x] Implement type inference in annotate comparison operator.
- [x] Integrate this method in the system

**Comment by MTimmerije** [comment]
I don't mind getting started with this one I guess.

**Comment by MTimmerije** [comment]
PR #52 closes this.
