### ISSUE TITLE
Assignment 10: Final Report (group)

### ISSUE THREAD

**Issue by yuanzexiong** [HectorPeeters/fontoxpath#5]
tl;dr polish the report and make sure that they match the expectations from the rubric.

## Useful Link
- [Rubric](https://brightspace.tudelft.nl/d2l/common/dialogs/quickLink/quickLink.d2l?ou=281758&type=content&rcode=tudelft-660804)
- [Brightspace Assignment](https://brightspace.tudelft.nl/d2l/lms/dropbox/user/folder_submit_files.d2l?db=74385&grpid=384312&isprv=0&bp=0&ou=281758)
- [Example Reports](https://repository.tudelft.nl/islandora/search/?collection=education)

**Comment by MTimmerije** [comment]
Closing this one, since #160 is more complete.
