### ISSUE TITLE
Speed up Expression Evaluation

### ISSUE THREAD

**Issue by HectorPeeters** [HectorPeeters/fontoxpath#59]
# Description

Now that we have the additional type information, we should use this to make sure all expressions have an early return if the type data is known. This will drastically speed up the whole execution.

# Subtasks

- [x] Identifying all early returns/shortcuts that can be based on static typing.
- [x] Implementing these shortcuts.

# Nodes

- [x] Binop
- [x] Unop
- [x] ...

**Comment by MTimmerije** [comment]
This is a bit of a vague issue, I think we can probably make it more precise.

**Comment by MTimmerije** [comment]
Made it a little less vague.
