### ISSUE TITLE
Resolve TODOs

### ISSUE THREAD

**Issue by FBroy** [HectorPeeters/fontoxpath#77]
# Description

Resolve the different TODOs around the code base.

some of the TODOs can be searched using keyword `TODO: Annotation not yet implemented`

# Sub-tasks

- [ ] annotateContextItemExpr.ts
- [x] annotateBinaryOperator.ts
- [ ] annotateUnaryLookup.ts
- [x] annotateTypeswitchOperator.ts
- [x] annotateTypeSwitchOperator.ts
- [x] SequenceOperator.ts
- [x] Unary.ts
- [x] valueCompare.ts
- [x] builtInFunctions_dataTypeConstructors.ts

**Comment by MTimmerije** [comment]
Added other tasks to it.
